#!/usr/bin/env bash
SCRIPT_DIR=

LOCAL_CLAUDE_DIR="$SCRIPT_DIR";
PERSISTENT_DATA_SUBDIR_PATH="$LOCAL_CLAUDE_DIR/containerdata";
WORKSPACE_SUBDIR_PATH="$PERSISTENT_DATA_SUBDIR_PATH/workspace";
CLAUDE_CONFIG_SUBDIR_PATH="$PERSISTENT_DATA_SUBDIR_PATH/claude-data"
CLAUDE_IMAGE_NAME="secure-claude-cli";

function ensure_prerequisite_dirs {
    mkdir -p "$PERSISTENT_DATA_SUBDIR_PATH";
    mkdir -p "$WORKSPACE_SUBDIR_PATH";
    mkdir -p "$CLAUDE_CONFIG_SUBDIR_PATH";
}

function say {
    ARG="$1";

    if [[ -z "$ARG" ]]; then
        echo "Usage: say <ARG>"
        return 1;
    fi

    echo -e "$ARG";
    return 0;
}


function build-claude-image {
    say "Building secure claude image; Image will be called $CLAUDE_IMAGE_NAME";
    claude_releases_url=$(curl -fsSL https://claude.ai/install.sh | sed -n -E 's/GCS_BUCKET="(.*)"/\1/p');
    latest_release=$(curl -fsSL "$claude_releases_url/latest" | grep -iE '\d.\d.\d');
    say "Using latest release: $latest_release";
    docker build --build-arg CLAUDE_CODE_VERSION=$latest_release --no-cache -t "$CLAUDE_IMAGE_NAME" "$SCRIPT_DIR";
}

# Security recommendations for runtime:
#
# WITHOUT firewall (maximum security):
function claude_maxsec {
    say "Running in max security mode";
    docker run --read-only --tmpfs /tmp --tmpfs /var/tmp \
            --cap-drop=ALL \
            --security-opt=no-new-privileges:true \
            --user claude:claude \
            -it secure-claude-cli /bin/bash
}

# WITH firewall (reduced security for network isolation):
# THIS LINE:
#   "$SCRIPT_DIR/containerdata/claude-config":/home/claude/.claude
# will persist any/all data generated by using Claude.
function claude_default {
    say "Running in default mode";
    docker run --cap-add=NET_ADMIN --cap-add=NET_RAW \
            -v "$WORKSPACE_SUBDIR_PATH":/workspace \
            -v "$CLAUDE_CONFIG_SUBDIR_PATH":/home/claude/.claude \
            --tmpfs /tmp --tmpfs /var/tmp \
            --entrypoint="/usr/local/bin/claude-entrypoint.sh" \
            -it secure-claude-cli /bin/bash
}

function claude {
    ARGS="$@";
    local MAX_SECURITY=0;

    ensure_prerequisite_dirs;

    # Ensure that the requisite dirs are created in $SCRIPT_DIR/containerdata


    while [[ "$#" -gt 0 ]]; do
        case "$1" in
            -m|-s|--max-sec|--sec|--secure)
            MAX_SECURITY=1;
            ;;
            -h|--help)
            echo "Usage: $0 [--secure]"
            return 0;
            ;;
            *)
            echo "Unknown option: $1" >&2
            return 1;
            ;;
        esac
        shift # consume the current option
    done

    if [[ $MAX_SECURITY -gt 0 ]]; then
        claude_maxsec;
    else
        claude_default;
    fi

    return 0;
}

export claude;