#!/usr/bin/env sh

uuid="$(uuidgen)"
extension_type="$1"

echo "generating file with extension type: $extension_type"

if [ -z "$extension_type" ]; then
  echo "Extension type not provided; exiting"
  exit 1
else
  tmpfile="/tmp/${uuid}.${extension_type}"
  nvim "$tmpfile"
fi
